module.exports = {


	'signintag':'<div class=\"dropdown-content\"><form action=\"/login\" method=\"post\" id=\"loginform\"><p>Username</p><input class=\"inputforms\" type=\"text\" name=\"username\" placeholder=\"username\" required><br><p>Password</p><input class=\"inputforms\" type=\"password\" name=\"password\" placeholder=\"password\" required><input class=\"inputforms\" type=\"submit\" value=\"Login\"><a class=\"inputforms\" href=\"/register\">Register</a></form></div>',

	'loggedintag':'<div class=\"dropdown-content\"><form action=\"/logout\" method=\"post\" id=\"logoutform\"><input class=\"inputforms\" type=\"submit\" value=\"Logout\"></form><form action=\"/profile\" method=\"post\"><input class=\"inputforms\" type=\"submit\" value=\"Your profile\"></form></div>',

	'registerform':'<form action=\"/register\" method=\"post\" id=\"registerform\"><p class=\"title1\">Username</p><input class=\"registerinput\" type=\"text\" name=\"username\" placeholder=\"username\" required><br><p class=\"title1\">Password</p><input class=\"registerinput\" type=\"password\" name=\"password\" placeholder=\"password\" required><br><p class=\"title1\">Enter password again</p><input class=\"registerinput\" type=\"password\" name=\"password2\" placeholder=\"repeat password\" required><br><p class=\"title1\">E-Mail-Address (don\'t cheat, we will send you a registration e-mail!)</p><input class=\"registerinput\" type=\"email\" name=\"email\" placeholder=\"email address\" required><br><input class=\"registerinput\" type=\"submit\" value=\"Register\"></form>',

	'productfilter':'<p class=\"title1\">FILTER BY</p><p class=\"title1 title2\">Category</p><form action=\"/products\" method=\"post\" class=\"filtercontent\" name=\"tabledata\"> <select name=\"category\"><option value=\"all\">Show all categories</option> <option>Balls</option> <option>Books</option> <option>Brooms</option> <option>Clothing</option></select><input type=\"submit\" value=\"Okay\"></form> ',

	'notworking':'<p id=\"notworking\"> </p>',

	'changeforms':'<form action=\"/changeUsername\" method=\"post\" id=\"changeuserform\"><p class=\"title1\">Change Username</p><br><input class=\"registerinput\" type=\"text\" name=\"username\" placeholder=\"username\" required><br><input class=\"registerinput\" type=\"password\" name=\"password\" placeholder=\"password\" required><br><input class=\"registerinput\" type=\"submit\" value=\"Submit\"><br><br><br></form><form action=\"/changePassword\" method=\"post\" id=\"changepwform\"><p class=\"title1\">Change Password</p><br><input class=\"registerinput\" type=\"password\" name=\"password\" placeholder=\"Current password\" required><br><input class=\"registerinput\" type=\"password\" name=\"newpassword\" placeholder=\"New password\" required><br><input class=\"registerinput\" type=\"password\" name=\"newpassword2\" placeholder=\"Repeat new password\" required><br><input class=\"registerinput\" type=\"submit\" value=\"Submit\"><br><br><br></form><form action=\"/changeEmail\" method=\"post\" id=\"changeemailform\"><p class=\"title1\">Change Email Address</p><br><p>To confirm your new email address you will get a confirmation email. You will have to click the link in the email to be able to log in again.</p><br><input class=\"registerinput\" type=\"email\" name=\"email\" placeholder=\"New email address\" required><br><input class=\"registerinput\" type=\"password\" name=\"password\" placeholder=\"Password\" required><br><input class=\"registerinput\" type=\"submit\" value=\"Submit\"><br><br><br></form><form action=\"/deleteUser\" method=\"post\" id=\"deleteform\"><p class=\"title1\">Delete Account</p><br><input class=\"registerinput\" type=\"password\" name=\"password\" placeholder=\"Password\" required><br><input class=\"registerinput\" type=\"submit\" value=\"Submit\" onclick=deleteUser()><br><br></form>'

} 